/* 지표 레지스트리 — scripts/build_indicators.py 가 생성한다. 직접 고치지 말 것.
 *
 * 한 지표 = 한 행. 화면·분류·중요도를 여기 한 곳에서만 정한다(IA 개편 v3 P0).
 *   asset      자산군 = 1차 네비 축 (index·equity·fx·rate·commodity·macro·realestate·sentiment·flow)
 *   topic      거시 주제 탭 (growth·price·labor·money·trade·demand)
 *   tier       1=대표(홈) 2=주요(자산군 화면) 3=상세 표 전용
 *   canonical  원본 화면. 다른 화면의 같은 값은 요약이며 원본으로 연결한다
 *   news       data.json.news 16주제 중 맥락 한 줄을 뽑을 키
 *   data       data.json 안의 현재값 경로 · series 는 시계열 경로
 *   merLens    mer_signals.json 의 같은 지표 id
 *   onScreen   false = 수집은 되는데 아직 어느 화면에도 없다(처리 대상)
 *
 * 생성 시각 기준 지표 122 · 데이터셋 19 · 미노출 15.
 */
(function () {
  var ROWS = [
    {"id": "kosdaq", "label": "KOSDAQ", "asset": "index", "data": "indices.KOSDAQ", "series": "history.indices.KOSDAQ", "tier": 1, "canonical": "market#index", "news": "주식", "aliases": ["KOSDAQ"], "keywords": ["코스닥", "주가", "증시"], "merLens": "kosdaq"},
    {"id": "kospi", "label": "KOSPI", "asset": "index", "data": "indices.KOSPI", "series": "history.indices.KOSPI", "tier": 1, "canonical": "market#index", "news": "주식", "aliases": ["KOSPI", "KOSPI 지수"], "keywords": ["코스피", "주가", "증시"], "merLens": "kospi"},
    {"id": "nasdaq", "label": "NASDAQ", "asset": "index", "data": "indices.NASDAQ", "series": "history.indices.NASDAQ", "tier": 1, "canonical": "market#index", "news": "주식", "aliases": ["NASDAQ"], "keywords": ["나스닥", "미국 증시", "미장"]},
    {"id": "nikkei", "label": "닛케이 225", "asset": "index", "data": "indices.Nikkei", "series": "history.indices.Nikkei", "tier": 1, "canonical": "market#index", "news": "주식", "aliases": ["닛케이", "닛케이 225"], "merLens": "nikkei"},
    {"id": "sp500", "label": "S&P 500", "asset": "index", "data": "indices.SP500", "series": "history.indices.SP500", "tier": 1, "canonical": "market#index", "news": "주식", "aliases": ["S&P 500", "S&P500"], "keywords": ["미국 증시", "미장"], "merLens": "us_equity"},
    {"id": "shanghai", "label": "상하이종합", "asset": "index", "data": "indices.Shanghai", "series": "history.indices.Shanghai", "tier": 2, "canonical": "market#index", "news": "주식", "merLens": "china_equity"},
    {"id": "sox", "label": "필라델피아 반도체", "asset": "index", "data": "indices.SOX", "series": "history.indices.SOX", "tier": 2, "canonical": "market#index", "news": "주식", "merLens": "semis"},
    {"id": "btc", "label": "BTC", "asset": "index", "data": "history.crypto.BTC", "series": "history.crypto.BTC", "tier": 3, "canonical": "market#index", "news": "주식", "keywords": ["비트코인", "코인", "가상자산"], "collectOnly": "시장>지수 탭에 가상자산 카드 1장으로 노출 예정(P3). 그때까지 수집만.", "merLens": "crypto"},
    {"id": "eurkrw", "label": "EUR/KRW", "asset": "fx", "data": "fx.EURKRW", "series": "history.fx.EURKRW", "tier": 1, "canonical": "market#fx", "news": "외환", "aliases": ["EUR/KRW", "EUR / KRW"], "keywords": ["유로 환율"]},
    {"id": "usdkrw", "label": "USD/KRW", "asset": "fx", "data": "fx.USDKRW", "series": "history.fx.USDKRW", "tier": 1, "canonical": "market#fx", "news": "외환", "aliases": ["USD/KRW", "USD / KRW", "달러/원"], "keywords": ["환율", "달러", "원달러", "달러원"], "merLens": "usdkrw"},
    {"id": "eurusd", "label": "EUR/USD", "asset": "fx", "data": "fx.EURUSD", "series": "history.fx.EURUSD", "tier": 2, "canonical": "market#fx", "news": "외환"},
    {"id": "jpykrw", "label": "JPY(100)/KRW", "asset": "fx", "data": "fx.JPYKRW", "series": "history.fx.JPYKRW", "tier": 2, "canonical": "market#fx", "news": "외환", "keywords": ["엔화", "엔 환율"]},
    {"id": "usdjpy", "label": "USD/JPY", "asset": "fx", "data": "fx.USDJPY", "series": "history.fx.USDJPY", "tier": 2, "canonical": "market#fx", "news": "외환", "keywords": ["엔화", "엔 환율"], "merLens": "usdjpy"},
    {"id": "us10y", "label": "미국 국채 10Y", "unit": "%", "asset": "rate", "data": "yieldCurve.us:10Y", "tier": 1, "canonical": "market#bond", "news": "채권", "aliases": ["미 10년물", "미국 10년물", "미국채 10년물"], "keywords": ["미국 금리", "국채", "장기금리"], "alsoData": ["economicIndicators.us.us10y"], "merLens": "us10y"},
    {"id": "kr10y", "label": "한국 국채 10Y", "unit": "%", "asset": "rate", "data": "yieldCurve.kr:10Y", "tier": 2, "canonical": "market#bond", "news": "채권", "keywords": ["국고채", "국채", "금리"], "merLens": "kr10y"},
    {"id": "us2y", "label": "미국 국채 2Y", "unit": "%", "asset": "rate", "data": "yieldCurve.us:2Y", "tier": 2, "canonical": "market#bond", "news": "채권", "alsoData": ["economicIndicators.us.us2y"], "merLens": "us2y"},
    {"id": "eu10y", "label": "유로존 국채 10Y", "unit": "%", "asset": "rate", "data": "yieldCurve.eu:10Y", "tier": 3, "canonical": "market#bond", "news": "채권"},
    {"id": "jp10y", "label": "일본 국채 10Y", "unit": "%", "asset": "rate", "data": "yieldCurve.jp:10Y", "tier": 3, "canonical": "market#bond", "news": "채권", "merLens": "jgb30y"},
    {"id": "uk10y", "label": "영국 국채 10Y", "unit": "%", "asset": "rate", "data": "yieldCurve.uk:10Y", "tier": 3, "canonical": "market#bond", "news": "채권"},
    {"id": "us30y", "label": "미국 국채 30Y", "unit": "%", "asset": "rate", "data": "yieldCurve.us:30Y", "tier": 3, "canonical": "market#bond", "news": "채권", "merLens": "us30y"},
    {"id": "brent", "label": "브렌트유", "asset": "commodity", "data": "commodities.Brent", "series": "history.commodities.Brent", "tier": 1, "canonical": "market#commodity", "news": "원유", "aliases": ["BRENT", "브렌트유"], "keywords": ["유가", "원유"]},
    {"id": "gold", "label": "금", "asset": "commodity", "data": "commodities.Gold", "series": "history.commodities.Gold", "tier": 1, "canonical": "market#commodity", "news": "귀금속", "aliases": ["금(GOLD)", "금(Gold)", "금"], "keywords": ["금값", "귀금속"], "merLens": "gold"},
    {"id": "wti", "label": "WTI 원유", "asset": "commodity", "data": "commodities.WTI", "series": "history.commodities.WTI", "tier": 1, "canonical": "market#commodity", "news": "원유", "aliases": ["WTI", "WTI 유가", "WTI 원유"], "keywords": ["유가", "기름값", "원유"], "merLens": "oil"},
    {"id": "copper", "label": "구리", "asset": "commodity", "data": "commodities.Copper", "series": "history.commodities.Copper", "tier": 2, "canonical": "market#commodity", "news": "비철금속", "keywords": ["구리", "비철"], "merLens": "copper"},
    {"id": "natgas", "label": "천연가스", "asset": "commodity", "data": "commodities.NatGas", "series": "history.commodities.NatGas", "tier": 2, "canonical": "market#commodity", "news": "원유", "merLens": "lng"},
    {"id": "silver", "label": "은", "asset": "commodity", "data": "commodities.Silver", "series": "history.commodities.Silver", "tier": 2, "canonical": "market#commodity", "news": "귀금속", "keywords": ["은값", "귀금속"], "merLens": "silver"},
    {"id": "aluminum", "label": "알루미늄", "asset": "commodity", "data": "commodities.Aluminum", "series": "history.commodities.Aluminum", "tier": 3, "canonical": "market#commodity", "news": "비철금속"},
    {"id": "cocoa", "label": "코코아", "asset": "commodity", "data": "commodities.Cocoa", "series": "history.commodities.Cocoa", "tier": 3, "canonical": "market#commodity", "news": "원자재"},
    {"id": "coffee", "label": "커피", "asset": "commodity", "data": "commodities.Coffee", "series": "history.commodities.Coffee", "tier": 3, "canonical": "market#commodity", "news": "원자재"},
    {"id": "corn", "label": "옥수수", "asset": "commodity", "data": "commodities.Corn", "series": "history.commodities.Corn", "tier": 3, "canonical": "market#commodity", "news": "원자재", "merLens": "agri"},
    {"id": "dubai", "label": "Dubai", "asset": "commodity", "data": "commodities.Dubai", "series": "history.commodities.Dubai", "tier": 3, "canonical": "market#commodity", "news": "원자재"},
    {"id": "gasoline", "label": "Gasoline", "asset": "commodity", "data": "commodities.Gasoline", "series": "history.commodities.Gasoline", "tier": 3, "canonical": "market#commodity", "news": "원자재", "merLens": "gasoline"},
    {"id": "heatingoil", "label": "HeatingOil", "asset": "commodity", "data": "commodities.HeatingOil", "series": "history.commodities.HeatingOil", "tier": 3, "canonical": "market#commodity", "news": "원자재"},
    {"id": "palladium", "label": "팔라듐", "asset": "commodity", "data": "commodities.Palladium", "series": "history.commodities.Palladium", "tier": 3, "canonical": "market#commodity", "news": "귀금속"},
    {"id": "platinum", "label": "백금", "asset": "commodity", "data": "commodities.Platinum", "series": "history.commodities.Platinum", "tier": 3, "canonical": "market#commodity", "news": "귀금속"},
    {"id": "rice", "label": "쌀", "asset": "commodity", "data": "commodities.Rice", "series": "history.commodities.Rice", "tier": 3, "canonical": "market#commodity", "news": "원자재"},
    {"id": "soybean", "label": "대두", "asset": "commodity", "data": "commodities.Soybean", "series": "history.commodities.Soybean", "tier": 3, "canonical": "market#commodity", "news": "원자재"},
    {"id": "sugar", "label": "설탕", "asset": "commodity", "data": "commodities.Sugar", "series": "history.commodities.Sugar", "tier": 3, "canonical": "market#commodity", "news": "원자재"},
    {"id": "wheat", "label": "밀", "asset": "commodity", "data": "commodities.Wheat", "series": "history.commodities.Wheat", "tier": 3, "canonical": "market#commodity", "news": "원자재"},
    {"id": "base_rate_kr", "label": "기준금리", "unit": "% (연이율)", "asset": "macro", "topic": "money", "cat": "통화", "country": "kr", "data": "economicIndicators.kr.base_rate_kr", "onScreen": true, "tier": 1, "canonical": "market#rate", "news": "한국은행", "aliases": ["한국 기준금리", "기준금리"], "keywords": ["기준금리", "한국은행", "금리"], "merLens": "bok_rate"},
    {"id": "cpi_kr", "label": "소비자물가지수 (CPI)", "unit": "지수 (2020=100)", "asset": "macro", "topic": "price", "cat": "물가", "country": "kr", "data": "economicIndicators.kr.cpi_kr", "onScreen": true, "tier": 2, "canonical": "macro", "keywords": ["물가", "인플레이션"], "merLens": "cpi_kr"},
    {"id": "cpi_us", "label": "소비자물가지수 (CPI)", "unit": "지수 (1982-84=100)", "asset": "macro", "topic": "price", "cat": "물가", "country": "us", "data": "economicIndicators.us.cpi_us", "onScreen": true, "tier": 2, "canonical": "macro", "news": "미국CPI", "keywords": ["물가", "인플레이션", "미국 물가"], "merLens": "core_cpi_us"},
    {"id": "exports_kr", "label": "수출", "unit": "백만달러", "asset": "macro", "topic": "trade", "cat": "무역", "country": "kr", "data": "economicIndicators.kr.exports_kr", "onScreen": true, "tier": 2, "canonical": "macro", "news": "한국수출", "merLens": "kr_exports"},
    {"id": "ff_target", "label": "미국 기준금리 목표 상한 (FOMC 발표)", "unit": null, "asset": "macro", "topic": "growth", "cat": null, "country": "us", "data": "economicIndicators.us.ff_target", "onScreen": true, "tier": 2, "canonical": "market#rate", "keywords": ["연준", "정책금리", "FOMC"], "merLens": "ff_target"},
    {"id": "gdp_kr", "label": "GDP 성장률 (전기비)", "unit": "% (전기비)", "asset": "macro", "topic": "growth", "cat": "경기", "country": "kr", "data": "economicIndicators.kr.gdp_kr", "onScreen": true, "tier": 2, "canonical": "macro", "news": "한국GDP"},
    {"id": "gdp_us", "label": "미국 GDP (연환산, 조달러)", "unit": null, "asset": "macro", "topic": "growth", "cat": null, "country": "us", "data": "economicIndicators.us.gdp_us", "onScreen": false, "tier": 2, "canonical": "macro"},
    {"id": "t10y2y_us", "label": "미국 장단기 금리차 10Y-2Y (일간, %p)", "unit": null, "asset": "macro", "topic": "growth", "cat": null, "country": "us", "data": "economicIndicators.us.t10y2y_us", "onScreen": false, "tier": 2, "canonical": "market#bond", "merLens": "t10y2y"},
    {"id": "unemployment_kr", "label": "실업률", "unit": "% (계절조정)", "asset": "macro", "topic": "labor", "cat": "고용", "country": "kr", "data": "economicIndicators.kr.unemployment_kr", "onScreen": true, "tier": 2, "canonical": "macro", "keywords": ["고용", "실업"]},
    {"id": "vix", "label": "VIX", "unit": "지수 (S&P500 30일 내재변동성)", "asset": "macro", "topic": "growth", "cat": "시장", "country": "us", "data": "economicIndicators.us.vix", "onScreen": true, "tier": 2, "canonical": "dashboard#mood", "keywords": ["변동성", "공포"], "merLens": "vix"},
    {"id": "base_rate_eu", "label": "기준금리 (ECB)", "unit": "% (예금금리)", "asset": "macro", "topic": "money", "cat": "통화", "country": "eu", "data": "economicIndicators.eu.base_rate_eu", "onScreen": true, "tier": 3, "canonical": "market#rate"},
    {"id": "base_rate_jp", "label": "기준금리 (BOJ)", "unit": "% (무담보 익일물)", "asset": "macro", "topic": "money", "cat": "통화", "country": "jp", "data": "economicIndicators.jp.base_rate_jp", "onScreen": true, "tier": 3, "canonical": "market#rate", "merLens": "boj_rate"},
    {"id": "base_rate_uk", "label": "기준금리 (BOE)", "unit": "% (Bank Rate)", "asset": "macro", "topic": "money", "cat": "통화", "country": "uk", "data": "economicIndicators.uk.base_rate_uk", "onScreen": true, "tier": 3, "canonical": "market#rate"},
    {"id": "bond10y_jp", "label": "일본 10년 국채 (월별)", "unit": null, "asset": "macro", "topic": "growth", "cat": null, "country": "jp", "data": "economicIndicators.jp.bond10y_jp", "onScreen": false, "tier": 3, "canonical": "market#bond"},
    {"id": "broad_dollar", "label": "달러 인덱스 (브로드, 2006=100)", "unit": null, "asset": "macro", "topic": "growth", "cat": null, "country": "us", "data": "economicIndicators.us.broad_dollar", "onScreen": false, "tier": 3, "canonical": "macro"},
    {"id": "claims_us", "label": "미국 신규 실업수당 청구 (주간, 명)", "unit": null, "asset": "macro", "topic": "growth", "cat": null, "country": "us", "data": "economicIndicators.us.claims_us", "onScreen": false, "tier": 3, "canonical": "macro"},
    {"id": "cpi_cn", "label": "소비자물가지수 (CPI)", "unit": "지수 (2015=100)", "asset": "macro", "topic": "price", "cat": "물가", "country": "cn", "data": "economicIndicators.cn.cpi_cn", "onScreen": true, "tier": 3, "canonical": "macro"},
    {"id": "cpi_de", "label": "소비자물가지수", "unit": "지수 (2015=100)", "asset": "macro", "topic": "price", "cat": "물가", "country": "de", "data": "economicIndicators.de.cpi_de", "onScreen": true, "tier": 3, "canonical": "macro"},
    {"id": "cpi_eu", "label": "HICP 물가지수", "unit": "지수 (2015=100)", "asset": "macro", "topic": "price", "cat": "물가", "country": "eu", "data": "economicIndicators.eu.cpi_eu", "onScreen": true, "tier": 3, "canonical": "macro"},
    {"id": "cpi_uk", "label": "소비자물가지수", "unit": "지수 (2015=100)", "asset": "macro", "topic": "price", "cat": "물가", "country": "uk", "data": "economicIndicators.uk.cpi_uk", "onScreen": true, "tier": 3, "canonical": "macro"},
    {"id": "current_account_kr", "label": "경상수지", "unit": "백만달러", "asset": "macro", "topic": "trade", "cat": "무역", "country": "kr", "data": "economicIndicators.kr.current_account_kr", "onScreen": true, "tier": 3, "canonical": "macro", "merLens": "current_account_kr"},
    {"id": "dxy_idx", "label": "달러 인덱스 (DXY)", "unit": "지수 (1973=100, ICE 발표)", "asset": "macro", "topic": "trade", "cat": "외환", "country": "us", "data": "economicIndicators.us.dxy_idx", "onScreen": true, "tier": 3, "canonical": "market#fx", "merLens": "dxy"},
    {"id": "ff_rate", "label": "기준금리 (FFR)", "unit": "% (연이율)", "asset": "macro", "topic": "money", "cat": "통화", "country": "us", "data": "economicIndicators.us.ff_rate", "onScreen": true, "tier": 3, "canonical": "macro"},
    {"id": "fx_reserves_kr", "label": "한국 외환보유액 (금 제외, IMF IFS, 백만USD)", "unit": null, "asset": "macro", "topic": "growth", "cat": null, "country": "kr", "data": "economicIndicators.kr.fx_reserves_kr", "onScreen": false, "tier": 3, "canonical": "macro", "merLens": "fx_reserves"},
    {"id": "gdp_cn", "label": "중국 GDP (USD)", "unit": null, "asset": "macro", "topic": "growth", "cat": null, "country": "cn", "data": "economicIndicators.cn.gdp_cn", "onScreen": false, "tier": 3, "canonical": "macro", "news": "중국경기"},
    {"id": "gdp_de", "label": "독일 실질GDP", "unit": null, "asset": "macro", "topic": "growth", "cat": null, "country": "de", "data": "economicIndicators.de.gdp_de", "onScreen": false, "tier": 3, "canonical": "macro", "news": "독일경기"},
    {"id": "gdp_eu", "label": "유로존 실질GDP (백만유로)", "unit": null, "asset": "macro", "topic": "growth", "cat": null, "country": "eu", "data": "economicIndicators.eu.gdp_eu", "onScreen": false, "tier": 3, "canonical": "macro", "news": "유로존"},
    {"id": "gdp_growth_us", "label": "GDP 성장률", "unit": "% (전기비 연율 SAAR)", "asset": "macro", "topic": "growth", "cat": "경기", "country": "us", "data": "economicIndicators.us.gdp_growth_us", "onScreen": true, "tier": 3, "canonical": "macro", "merLens": "gdp_growth_us"},
    {"id": "gdp_jp", "label": "일본 실질GDP (분기, 십억엔)", "unit": null, "asset": "macro", "topic": "growth", "cat": null, "country": "jp", "data": "economicIndicators.jp.gdp_jp", "onScreen": true, "tier": 3, "canonical": "macro", "news": "일본경기"},
    {"id": "gdp_uk", "label": "영국 실질GDP (분기, IMF)", "unit": null, "asset": "macro", "topic": "growth", "cat": null, "country": "uk", "data": "economicIndicators.uk.gdp_uk", "onScreen": false, "tier": 3, "canonical": "macro", "news": "영국경기"},
    {"id": "gdp_yoy_cn", "label": "GDP 성장률", "unit": "% (YoY, 명목 USD)", "asset": "macro", "topic": "growth", "cat": "경기", "country": "cn", "data": "economicIndicators.cn.gdp_yoy_cn", "onScreen": true, "tier": 3, "canonical": "macro"},
    {"id": "gdp_yoy_de", "label": "GDP 성장률", "unit": "% (YoY, 실질)", "asset": "macro", "topic": "growth", "cat": "경기", "country": "de", "data": "economicIndicators.de.gdp_yoy_de", "onScreen": true, "tier": 3, "canonical": "macro"},
    {"id": "gdp_yoy_eu", "label": "GDP 성장률", "unit": "% (YoY, 실질)", "asset": "macro", "topic": "growth", "cat": "경기", "country": "eu", "data": "economicIndicators.eu.gdp_yoy_eu", "onScreen": true, "tier": 3, "canonical": "macro"},
    {"id": "gdp_yoy_jp", "label": "GDP 성장률", "unit": "% (YoY, 실질)", "asset": "macro", "topic": "growth", "cat": "경기", "country": "jp", "data": "economicIndicators.jp.gdp_yoy_jp", "onScreen": true, "tier": 3, "canonical": "macro"},
    {"id": "gdp_yoy_uk", "label": "GDP 성장률", "unit": "% (YoY, 실질)", "asset": "macro", "topic": "growth", "cat": "경기", "country": "uk", "data": "economicIndicators.uk.gdp_yoy_uk", "onScreen": true, "tier": 3, "canonical": "macro"},
    {"id": "household_debt_kr", "label": "한국 가계신용 잔액 (10억원) — KeyStat:가계신용", "unit": null, "asset": "macro", "topic": "growth", "cat": null, "country": "kr", "data": "economicIndicators.kr.household_debt_kr", "onScreen": true, "tier": 3, "canonical": "macro"},
    {"id": "hy_spread", "label": "HY 크레딧 스프레드", "unit": "%p (국채 대비)", "asset": "macro", "topic": "growth", "cat": "시장", "country": "us", "data": "economicIndicators.us.hy_spread", "onScreen": true, "tier": 3, "canonical": "market#bond", "merLens": "hy_spread"},
    {"id": "ip_kr", "label": "산업생산지수", "unit": "지수 (2020=100)", "asset": "macro", "topic": "growth", "cat": "경기", "country": "kr", "data": "economicIndicators.kr.ip_kr", "onScreen": true, "tier": 3, "canonical": "macro"},
    {"id": "ip_us", "label": "산업생산지수", "unit": "지수 (2017=100, 계절조정)", "asset": "macro", "topic": "growth", "cat": "경기", "country": "us", "data": "economicIndicators.us.ip_us", "onScreen": true, "tier": 3, "canonical": "macro"},
    {"id": "m2_us", "label": "M2 통화량", "unit": "10억 USD", "asset": "macro", "topic": "money", "cat": "통화", "country": "us", "data": "economicIndicators.us.m2_us", "onScreen": true, "tier": 3, "canonical": "macro"},
    {"id": "mortgage_rate_kr", "label": "한국 주담대 평균금리 (신규)", "unit": null, "asset": "macro", "topic": "growth", "cat": null, "country": "kr", "data": "economicIndicators.kr.mortgage_rate_kr", "onScreen": true, "tier": 3, "canonical": "macro"},
    {"id": "nfp_us", "label": "미국 비농업고용 (PAYEMS, 천명)", "unit": null, "asset": "macro", "topic": "growth", "cat": null, "country": "us", "data": "economicIndicators.us.nfp_us", "onScreen": true, "tier": 3, "canonical": "macro"},
    {"id": "pce_us", "label": "PCE 물가지수", "unit": "지수 (2017=100)", "asset": "macro", "topic": "price", "cat": "물가", "country": "us", "data": "economicIndicators.us.pce_us", "onScreen": true, "tier": 3, "canonical": "macro", "merLens": "pce_us"},
    {"id": "pmi_cn", "label": "제조업 PMI·경기지수", "unit": "지수", "asset": "macro", "topic": "growth", "cat": "경기", "country": "cn", "data": "economicIndicators.cn.pmi_cn", "onScreen": true, "tier": 3, "canonical": "macro", "news": "중국경기"},
    {"id": "pmi_de", "label": "제조업 PMI·경기지수", "unit": "지수", "asset": "macro", "topic": "growth", "cat": "경기", "country": "de", "data": "economicIndicators.de.pmi_de", "onScreen": true, "tier": 3, "canonical": "macro", "news": "독일경기"},
    {"id": "pmi_eu", "label": "제조업 PMI·경기지수", "unit": "지수", "asset": "macro", "topic": "growth", "cat": "경기", "country": "eu", "data": "economicIndicators.eu.pmi_eu", "onScreen": true, "tier": 3, "canonical": "macro", "news": "유로존"},
    {"id": "pmi_jp", "label": "제조업 PMI·경기지수", "unit": "지수", "asset": "macro", "topic": "growth", "cat": "경기", "country": "jp", "data": "economicIndicators.jp.pmi_jp", "onScreen": true, "tier": 3, "canonical": "macro", "news": "일본경기"},
    {"id": "pmi_kr", "label": "제조업 PMI·경기지수", "unit": "지수", "asset": "macro", "topic": "growth", "cat": "경기", "country": "kr", "data": "economicIndicators.kr.pmi_kr", "onScreen": true, "tier": 3, "canonical": "macro"},
    {"id": "pmi_uk", "label": "제조업 PMI·경기지수", "unit": "지수", "asset": "macro", "topic": "growth", "cat": "경기", "country": "uk", "data": "economicIndicators.uk.pmi_uk", "onScreen": true, "tier": 3, "canonical": "macro", "news": "영국경기"},
    {"id": "pmi_us", "label": "제조업 PMI·경기지수", "unit": "지수", "asset": "macro", "topic": "growth", "cat": "경기", "country": "us", "data": "economicIndicators.us.pmi_us", "onScreen": true, "tier": 3, "canonical": "macro"},
    {"id": "ppi_kr", "label": "생산자물가지수 (PPI)", "unit": "지수 (2015=100)", "asset": "macro", "topic": "price", "cat": "물가", "country": "kr", "data": "economicIndicators.kr.ppi_kr", "onScreen": true, "tier": 3, "canonical": "macro"},
    {"id": "ppi_us", "label": "미국 PPI 최종재 (월간, Final Demand)", "unit": null, "asset": "macro", "topic": "growth", "cat": null, "country": "us", "data": "economicIndicators.us.ppi_us", "onScreen": true, "tier": 3, "canonical": "macro"},
    {"id": "reserves_us", "label": "미 지급준비금 잔액 (주간, 백만USD)", "unit": null, "asset": "macro", "topic": "growth", "cat": null, "country": "us", "data": "economicIndicators.us.reserves_us", "onScreen": false, "tier": 3, "canonical": "macro", "merLens": "reserves"},
    {"id": "retail_kr", "label": "소매판매액지수", "unit": "지수 (2020=100)", "asset": "macro", "topic": "demand", "cat": "소비", "country": "kr", "data": "economicIndicators.kr.retail_kr", "onScreen": true, "tier": 3, "canonical": "macro"},
    {"id": "retail_us", "label": "미국 소매판매 (수정후, 백만USD)", "unit": null, "asset": "macro", "topic": "growth", "cat": null, "country": "us", "data": "economicIndicators.us.retail_us", "onScreen": true, "tier": 3, "canonical": "macro"},
    {"id": "rrp_us", "label": "미 역레포 잔액 (일간, 십억USD)", "unit": null, "asset": "macro", "topic": "growth", "cat": null, "country": "us", "data": "economicIndicators.us.rrp_us", "onScreen": false, "tier": 3, "canonical": "macro", "merLens": "rrp"},
    {"id": "sentiment_us", "label": "미국 소비자심리지수 (미시간대)", "unit": null, "asset": "macro", "topic": "growth", "cat": null, "country": "us", "data": "economicIndicators.us.sentiment_us", "onScreen": false, "tier": 3, "canonical": "macro"},
    {"id": "tga_us", "label": "미 재무부 일반계정 TGA (주간, 백만USD)", "unit": null, "asset": "macro", "topic": "growth", "cat": null, "country": "us", "data": "economicIndicators.us.tga_us", "onScreen": false, "tier": 3, "canonical": "macro", "merLens": "tga"},
    {"id": "unemployment", "label": "실업률", "unit": "% (계절조정)", "asset": "macro", "topic": "labor", "cat": "고용", "country": "us", "data": "economicIndicators.us.unemployment", "onScreen": true, "tier": 3, "canonical": "macro", "merLens": "employment"},
    {"id": "unemployment_de", "label": "실업률", "unit": "% (계절조정)", "asset": "macro", "topic": "labor", "cat": "고용", "country": "de", "data": "economicIndicators.de.unemployment_de", "onScreen": true, "tier": 3, "canonical": "macro"},
    {"id": "unemployment_eu", "label": "실업률", "unit": "% (계절조정)", "asset": "macro", "topic": "labor", "cat": "고용", "country": "eu", "data": "economicIndicators.eu.unemployment_eu", "onScreen": true, "tier": 3, "canonical": "macro"},
    {"id": "unemployment_jp", "label": "실업률", "unit": "% (15-64세, 계절조정)", "asset": "macro", "topic": "labor", "cat": "고용", "country": "jp", "data": "economicIndicators.jp.unemployment_jp", "onScreen": true, "tier": 3, "canonical": "macro"},
    {"id": "unemployment_uk", "label": "실업률", "unit": "% (계절조정)", "asset": "macro", "topic": "labor", "cat": "고용", "country": "uk", "data": "economicIndicators.uk.unemployment_uk", "onScreen": true, "tier": 3, "canonical": "macro"},
    {"id": "apt_price_idx_kr", "label": "전국주택가격동향조사 아파트 매매가격지수", "asset": "realestate", "topic": "kr", "data": "realestate.kr.apt_price_idx_kr", "onScreen": true, "tier": 3, "canonical": "realestate", "merLens": "realestate"},
    {"id": "building_permits_us", "label": "건축허가 (천 건, 연환산)", "asset": "realestate", "topic": "us", "data": "realestate.us.building_permits", "onScreen": true, "tier": 3, "canonical": "realestate"},
    {"id": "case_shiller_20city_us", "label": "Case-Shiller 20대도시 HPI", "asset": "realestate", "topic": "us", "data": "realestate.us.case_shiller_20city", "onScreen": true, "tier": 3, "canonical": "realestate"},
    {"id": "case_shiller_national_us", "label": "Case-Shiller HPI", "asset": "realestate", "topic": "us", "data": "realestate.us.case_shiller_national", "onScreen": true, "tier": 3, "canonical": "realestate"},
    {"id": "case_shiller_state_us", "label": "case_shiller_state", "asset": "realestate", "topic": "us", "data": "realestate.us.case_shiller_state", "onScreen": true, "tier": 3, "canonical": "realestate"},
    {"id": "conversion_rate_kr", "label": "전월세전환율 (전국, 월)", "asset": "realestate", "topic": "kr", "data": "realestate.kr.conversion_rate_kr", "onScreen": true, "tier": 3, "canonical": "realestate"},
    {"id": "existing_home_sales_us", "label": "기존주택판매 (백만 건, 연환산)", "asset": "realestate", "topic": "us", "data": "realestate.us.existing_home_sales", "onScreen": true, "tier": 3, "canonical": "realestate"},
    {"id": "housing_starts_us", "label": "주택착공 (천 호, 연환산)", "asset": "realestate", "topic": "us", "data": "realestate.us.housing_starts", "onScreen": true, "tier": 3, "canonical": "realestate"},
    {"id": "jns_price_idx_kr", "label": "전국주택가격동향조사 주택종합 전세가격지수", "asset": "realestate", "topic": "kr", "data": "realestate.kr.jns_price_idx_kr", "onScreen": true, "tier": 3, "canonical": "realestate"},
    {"id": "mortgage_15y_us", "label": "15년 고정 모기지 금리 (%)", "asset": "realestate", "topic": "us", "data": "realestate.us.mortgage_15y", "onScreen": true, "tier": 3, "canonical": "realestate"},
    {"id": "mortgage_30y_us", "label": "30년 모기지", "asset": "realestate", "topic": "us", "data": "realestate.us.mortgage_30y", "onScreen": true, "tier": 3, "canonical": "realestate"},
    {"id": "nahb_index_us", "label": "NAHB 주택시장지수", "asset": "realestate", "topic": "us", "data": "realestate.us.nahb_index", "onScreen": true, "tier": 3, "canonical": "realestate"},
    {"id": "new_home_sales_us", "label": "신규주택판매 (천 건, 연환산)", "asset": "realestate", "topic": "us", "data": "realestate.us.new_home_sales", "onScreen": true, "tier": 3, "canonical": "realestate"},
    {"id": "start_kr", "label": "주택 착공 실적 (전국)", "asset": "realestate", "topic": "kr", "data": "realestate.kr.start_kr", "onScreen": true, "tier": 3, "canonical": "realestate"},
    {"id": "trade_count_kr", "label": "한국부동산원 행정구역별 아파트거래현황 (전국·동(호)수)", "asset": "realestate", "topic": "kr", "data": "realestate.kr.trade_count_kr", "onScreen": true, "tier": 3, "canonical": "realestate"},
    {"id": "trade_count_kr_rone_kr", "label": "한국부동산원 행정구역별 아파트거래현황 (전국·동(호)수)", "asset": "realestate", "topic": "kr", "data": "realestate.kr.trade_count_kr_rone", "onScreen": false, "tier": 3, "canonical": "realestate"},
    {"id": "unsold_kr", "label": "전국 미분양 주택 수", "asset": "realestate", "topic": "kr", "data": "realestate.kr.unsold_kr", "onScreen": true, "tier": 3, "canonical": "realestate"},
    {"id": "fear_greed", "label": "공포·탐욕 지수", "asset": "sentiment", "data": "sentiment.fear_greed", "tier": 2, "canonical": "dashboard#mood"},
    {"id": "move", "label": "MOVE", "asset": "sentiment", "data": "sentiment.move", "tier": 2, "canonical": "dashboard#mood", "merLens": "volatility"},
    {"id": "vkospi", "label": "V-KOSPI", "asset": "sentiment", "data": "sentiment.vkospi", "tier": 2, "canonical": "dashboard#mood", "keywords": ["변동성", "공포"], "merLens": "vkospi"},
  ];
  var SETS = [
    {"id": "macro_indicators", "label": "주요 경제 지표 전체", "asset": "macro", "canonical": "macro", "data": "economicIndicators", "aliases": ["주요 경제 지표 전체 (실시간)", "주요 경제 지표 전체", "주요 경제 지표"], "kind": "dataset", "tier": 2},
    {"id": "market_mood", "label": "시장 분위기", "asset": "sentiment", "canonical": "dashboard#mood", "data": "sentiment", "aliases": ["시장 분위기"], "kind": "dataset", "tier": 2},
    {"id": "apt_price_kr", "label": "아파트 가격지수 추이", "asset": "realestate", "canonical": "realestate", "data": "realestate.kr", "aliases": ["아파트 가격지수 추이", "아파트 가격지수"], "kind": "dataset", "tier": 2},
    {"id": "global_indices", "label": "글로벌 지수", "asset": "index", "canonical": "market#index", "data": "indices", "aliases": ["글로벌 지수", "글로벌 지수 현황", "글로벌 주요 지수"], "kind": "dataset", "tier": 2},
    {"id": "kospi_movers", "label": "등락 Top10", "asset": "equity", "canonical": "market#equity", "data": "stockMovers", "kind": "dataset", "tier": 2},
    {"id": "etf_movers", "label": "ETF 등락", "asset": "equity", "canonical": "market#equity", "data": "etfMovers", "kind": "dataset", "tier": 2},
    {"id": "rankings_kr", "label": "거래대금·토스 체결 순위", "asset": "equity", "canonical": "market#equity", "data": "rankingsKr", "kind": "dataset", "tier": 2},
    {"id": "investor_trading", "label": "투자자별 순매매", "asset": "flow", "canonical": "flow#investor", "data": "investorTrading", "kind": "dataset", "tier": 2, "merLens": "foreign_flow"},
    {"id": "stock_flows", "label": "종목별 수급·공매도·신용", "asset": "flow", "canonical": "flow#stock", "data": "stockFlows", "kind": "dataset", "tier": 2},
    {"id": "nps", "label": "국민연금 자산배분", "asset": "flow", "canonical": "flow#nps", "data": "nps", "aliases": ["국민연금 자산배분", "자산 배분 현황"], "kind": "dataset", "tier": 2, "merLens": "nps_kr_equity"},
    {"id": "lme_inventory", "label": "LME 금속 재고", "asset": "commodity", "canonical": "market#commodity", "data": "lmeInventory", "kind": "dataset", "tier": 2, "merLens": "lme_copper"},
    {"id": "freight", "label": "해상운임 지수", "asset": "commodity", "canonical": "market#commodity", "data": "freight", "aliases": ["해상운임 지수", "운송 운임지수 (해상운임)", "운송 운임지수"], "kind": "dataset", "tier": 2, "merLens": "freight_rate"},
    {"id": "subscription", "label": "청약 경쟁률", "asset": "realestate", "canonical": "realestate#kr", "data": "subscription", "kind": "dataset", "tier": 2},
    {"id": "economic_calendar", "label": "경제 일정", "asset": "macro", "canonical": "macro#calendar", "data": "economicCalendar", "kind": "dataset", "tier": 2},
    {"id": "market_calendar_kr", "label": "장 운영 일정", "asset": "macro", "canonical": "macro#calendar", "data": "marketCalendarKr", "kind": "dataset", "tier": 2},
    {"id": "climate", "label": "엘니뇨·라니냐", "asset": "commodity", "canonical": "market#commodity", "data": "climate", "kind": "dataset", "tier": 2},
    {"id": "news", "label": "뉴스", "asset": "macro", "canonical": "inline", "data": "news", "kind": "dataset", "tier": 2},
    {"id": "ai_briefing", "label": "AI 브리핑", "asset": "macro", "canonical": "dashboard", "data": "aiBriefing", "kind": "dataset", "tier": 2},
    {"id": "market_halts", "label": "서킷브레이커·사이드카", "asset": "equity", "canonical": "global-banner", "data": "marketHalts", "kind": "dataset", "tier": 2},
  ];
  var byId = {}, byPath = {}, byName = {};
  ROWS.concat(SETS).forEach(function (r) {
    byId[r.id] = r;
    if (r.data) byPath[r.data] = r;
    (r.alsoData || []).forEach(function (p) { byPath[p] = r; });
    [r.label].concat(r.aliases || []).forEach(function (n) {
      if (n && !byName[n]) byName[n] = r;
    });
  });
  window.ECON_IND = {
    rows: ROWS,
    datasets: SETS,
    get: function (id) { return byId[id] || null; },
    byPath: function (path) { return byPath[path] || null; },
    /* 화면에 쓰인 문자열(라벨·옛 이름)로 행을 찾는다 — 표기 통일의 대조표 */
    find: function (name) { return byName[name] || byId[name] || null; },
    label: function (id, fallback) { return (byId[id] && byId[id].label) || fallback || id; },
    tier: function (n) { return ROWS.filter(function (r) { return r.tier === n; }); },
    asset: function (a) { return ROWS.filter(function (r) { return r.asset === a; }); },
    topic: function (t) { return ROWS.filter(function (r) { return r.topic === t; }); },
    canonicalOf: function (id) { return (byId[id] || {}).canonical || null; },
    newsKeyOf: function (id) { return (byId[id] || {}).news || null; }
  };
})();
